### ISSUE TITLE
Multiple key activation

### ISSUE THREAD

**Issue by nicozimmermann94** [joshuaferrara/node-steam-key#1]
The activateKey function takes a callback function as the second parameter. Unfortunately this callback is not the same as the purchaseResponse event.
I want to activate multiple keys in one shot, but since I do not know when the responses come, I cannot match the response to the entered key.
Is there a way to distinguish which key activation belongs to which purchaseResponse event?

**Comment by joshuaferrara** [comment]
Were you able to activate multiple keys in one shot? I was unaware that this was a possibility as I thought there would be some sort of rate limiting.

I'd be careful with activating multiple in one-shot though if that's a possibility. The servers will eventually deny all requests to activate keys if you attempt to activate multiple invalid/used keys.

**Comment by nicozimmermann94** [comment]
You can activate up to 10 keys per hour. Maybe you can inject the activated key in the response callback object?

**Comment by joshuaferrara** [comment]
I'll check and see if that's possible in a few hours. Though I don't believe the key activation message allows for tagging them in that way (by using job IDs; this is possible for certain game coordinators though).

**Comment by joshuaferrara** [comment]
Did some research. Looks like there is a JobID associated with the registration action and the purchase response. (Look at the `jobid_source` and `jobid_target` in the images below). It should be possible to match these up and make the callback work better. Won't be able to work on it until I have some free time though.

`ClientRegisterKey`
![image](https://cloud.githubusercontent.com/assets/248680/12805860/d9f05dd0-cab4-11e5-9daf-09df66343343.png)

`ClientPurchaseResponse`
![image](https://cloud.githubusercontent.com/assets/248680/12805870/e995c964-cab4-11e5-8d70-394cdb9f7416.png)

**Comment by zumicts** [comment]
How are you debugging the steam client traffic?

**Comment by joshuaferrara** [comment]
@zumicts SteamKit.

**Comment by joshuaferrara** [comment]
Having no luck in sending `target_job_name`. I've also tried `trace_tag` but no results with that either.

**Comment by joshuaferrara** [comment]
Commit c34b1e91897c640ff9a90d7c0e52c1fbc1e62b2f fixes/adds callback functionality with the `activateKey` method.

**Comment by nicozimmermann94** [comment]
Thank you very much.
