### ISSUE TITLE
eresult: 85

### ISSUE THREAD

**Issue by FaNNboii** [joshuaferrara/node-steam-key#5]
I always get this error message.

Message from GC: 1303
Message from GC: 1305
error,  { eresult: 85,
  eresult_extended: 85,
  client_supplied_steamid: '**********************',
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0 }

I googled and its: AccountLogonDeniedNeedTwoFactorCode = 85
is it not comaptible with 2fa accs?

Best Regards,
Nico

**Comment by joshuaferrara** [comment]
See [node-steam-totp](https://github.com/DoctorMcKay/node-steam-totp) by @DoctorMcKay or disable 2FA.

This module has not been tested with 2FA though, so YMMV.
